<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>

    <OutputType>Exe</OutputType>

    <TargetFramework>net8.0-android34.0</TargetFramework>

    <Nullable>enable</Nullable>

    <ImplicitUsings>enable</ImplicitUsings>


    <ApplicationTitle>Umbaran Asset Browser</ApplicationTitle>

    <ApplicationId>com.umbaran.assetbrowser</ApplicationId>


    <SupportedOSPlatformVersion>34</SupportedOSPlatformVersion>

    <AndroidUseLatestPlatformSdk>true</AndroidUseLatestPlatformSdk>

    <AndroidPackageFormat>apk</AndroidPackageFormat>


    <!-- Hindari masalah Avalonia saat publish -->
    <PublishTrimmed>false</PublishTrimmed>

    <!-- Build lebih ringan di GitHub Actions -->
    <AndroidEnableProfiledAot>false</AndroidEnableProfiledAot>


  </PropertyGroup>


  <ItemGroup>

    <PackageReference Include="Avalonia"
                      Version="11.2.3" />


    <PackageReference Include="Avalonia.Android"
                      Version="11.2.3" />


    <PackageReference Include="Avalonia.Themes.Fluent"
                      Version="11.2.3" />


    <PackageReference Include="Avalonia.Fonts.Inter"
                      Version="11.2.3" />


  </ItemGroup>


</Project>
