<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>

    <OutputType>Exe</OutputType>

    <TargetFramework>net8.0-android34.0</TargetFramework>

    <Nullable>enable</Nullable>

    <ImplicitUsings>enable</ImplicitUsings>


    <ApplicationTitle>Umbaran Asset Browser</ApplicationTitle>

    <ApplicationId>com.umbaran.assetbrowser</ApplicationId>

    <ApplicationVersion>1</ApplicationVersion>

    <ApplicationDisplayVersion>0.1</ApplicationDisplayVersion>


    <SupportedOSPlatformVersion>23</SupportedOSPlatformVersion>

    <AndroidUseLatestPlatformSdk>true</AndroidUseLatestPlatformSdk>


    <!-- APK -->

    <AndroidPackageFormat>apk</AndroidPackageFormat>

    <AndroidPackageFormats>apk</AndroidPackageFormats>


    <!-- Target Mi A1 -->

    <RuntimeIdentifiers>android-arm64</RuntimeIdentifiers>


    <!-- Stabil dulu -->

    <PublishTrimmed>false</PublishTrimmed>

    <RunAOTCompilation>false</RunAOTCompilation>

    <AndroidEnableProfiledAot>false</AndroidEnableProfiledAot>


    <!-- Jangan buat split -->

    <AndroidCreatePackagePerAbi>false</AndroidCreatePackagePerAbi>


  </PropertyGroup>


  <ItemGroup>

    <PackageReference Include="Avalonia"
                      Version="11.2.3" />

    <PackageReference Include="Avalonia.Android"
                      Version="11.2.3" />

    <PackageReference Include="Avalonia.Themes.Fluent"
                      Version="11.2.3" />

    <PackageReference Include="Avalonia.Fonts.Inter"
                      Version="11.2.3" />

  </ItemGroup>


</Project>
