<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="AssetsTools.NET">
      <HintPath>..\Libs\AssetsTools.NET.dll</HintPath>
    </Reference>

    <Reference Include="AssetsTools.NET.Cpp2IL">
      <HintPath>..\Libs\AssetsTools.NET.Cpp2IL.dll</HintPath>
    </Reference>

    <Reference Include="AssetsTools.NET.MonoCecil">
      <HintPath>..\Libs\AssetsTools.NET.MonoCecil.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
