name: Build Android APK


on:
  workflow_dispatch:


jobs:

  android-build:

    runs-on: ubuntu-latest


    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'


      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.130'


      - name: Check dotnet
        run: |
          echo "=== DOTNET VERSION ==="
          dotnet --version
          dotnet --list-sdks


      - name: Install Android workload
        run: |
          dotnet workload install android


      - name: Debug Project Location
        run: |
          echo "=== CURRENT DIRECTORY ==="
          pwd

          echo ""
          echo "=== ALL CSPROJ ==="
          find . -name "*.csproj"

          echo ""
          echo "=== ANDROID PROJECT CONTENT ==="
          cat ./UmbaranAssetBrowserUI/UmbaranAssetBrowserUI.Android.csproj

          echo ""
          echo "=== SEARCH android21 ==="
          grep -R "android21" . || true

          echo ""
          echo "=== SEARCH TargetFramework ==="
          grep -R "TargetFramework" .


      - name: Restore Android project
        run: |
          dotnet restore ./UmbaranAssetBrowserUI/UmbaranAssetBrowserUI.Android.csproj


      - name: Build APK
        run: |
          dotnet build ./UmbaranAssetBrowserUI/UmbaranAssetBrowserUI.Android.csproj \
          -c Release \
          -f net8.0-android34.0 \
          /p:AndroidPackageFormat=apk


      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: UmbaranAssetBrowser-APK
          path: |
            UmbaranAssetBrowserUI/bin/Release/**/*.apk
