name: Build Android APK

on:
  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/dotnet/sdk:8.0


    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Install Java
        run: |
          apt update
          apt install -y openjdk-17-jdk


      - name: Check SDK
        run: |
          dotnet --version
          dotnet --list-sdks


      - name: Install Android workload
        run: |
          dotnet workload install android


      - name: Check project
        run: |
          cat UmbaranAssetBrowserUI/UmbaranAssetBrowserUI.Android.csproj


      - name: Restore
        run: |
          dotnet restore \
          UmbaranAssetBrowserUI/UmbaranAssetBrowserUI.Android.csproj


      - name: Build APK
        run: |
          dotnet build \
          UmbaranAssetBrowserUI/UmbaranAssetBrowserUI.Android.csproj \
          -c Release \
          -f net8.0-android34.0 \
          /p:AndroidPackageFormat=apk


      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: UmbaranAssetBrowser.apk
          path: |
            UmbaranAssetBrowserUI/bin/Release/**/*.apk
