name: Build TexToolWrap

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4


    - name: Install CMake
      run: |
        sudo apt update
        sudo apt install cmake build-essential


    - name: Build
      run: |
        mkdir build
        cd build
        cmake ../UmbaranTextureTool/TexToolWrap
        make


    - name: Show result
      run: |
        find build -name "*.so"
